### ISSUE TITLE
NCBI & CARD: DfrA18 and DfrA19 trimethoprim resistant dihydrofolate reductase

### ISSUE THREAD

**Issue by agmcarthur** [arpcard/amr_curation#1]
@arpcard has been cleaning up their curation of the antibiotic resistant dihydrofolate reductases, with more to come. NCBI has emailed the following:

We previously did this:

* AAK64581.1 dfr18 PMID: 11600347 “…whereas the gene conferring resistance to Tm, designated dfr18, is novel.”
* CAC81324.1 dfrA18 (as an allele of the DfrA18/DfrA19 family) PMID: 12002644 AJ310778.1 (as an allele of the DfrA18/DfrA19 family)
* ACO54029.1 dfrA19 (as an allele of the DfrA18/DfrA19 family) (one amino acid different from CAC81324.1)
 
However, it seems the authors of the dfrA18 paper came to decide that “dfr18” actually meant “dfrA18“ and they changed their name to “dfrA19” in the corresponding GenBank entry maybe 15 years ago.

NCBI's suggestion:

* CAC81324.1 and ACO54029.1 are both simply members of the DfrA19 family
* The family dfr18 to be renamed dfrA18

@arpcard will review these papers and nomenclature and will reply in the context of their entire review of the Dfrs.

**Comment by arpcard** [comment]
Added AAK64581.1 as dfrA18 in CARD. CAC81324.1 was already moved to dfrA19 as part of Matt's review.

**Comment by arpcard** [comment]
#card_preprint Evolution and Nomenclature of the Trimethoprim Resistant Dihydrofolate (dfr) Reductases https://www.preprints.org/manuscript/201905.0137/v1
