### ISSUE TITLE
correction for mtrR gene

### ISSUE THREAD

**Issue by Mor-Rubinsteinn** [arpcard/amr_curation#10]
Neisseria gonorrhoeae mtrR gene codes for a repressor of mtrCDE expression. Mutations in mtrR increase multidrug resistance, but not its wild type form. 
However in the CARD database it appears as a protein homolog model. Therefore, when a genome of Neisseria gonorrhoeae is analyzed in RGI in CARD, the presence of this gene, which is part of the core genome of the bacterium, is identified and indicated as predicting antibiotic resistance. 
Please change this gene from 'protein homolog model' to 'protein variant model'

Best regards, 
Mor Rubinstein
Bioinformatician
The National Public Health Laboratory
Tel Aviv
Israel

**Comment by arpcard** [comment]
Will be addressed in August 2019 patch release.

**Comment by arpcard** [comment]
Fixed: https://card.mcmaster.ca/ontology/37197
