### ISSUE TITLE
complete sequences for SHV-6, SHV-19 and SHV-84 beta-lactamases

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#101]
Hello,

Complete sequences are now available in GenBank for the SHV-6, SHV-19 and SHV-84 beta-lactamases. The old, partial sequences should be replaced by the complete ones as follows:

* [SHV-6](http://www.ncbi.nlm.nih.gov/pubmed/9228783): [CAA71948](http://www.ncbi.nlm.nih.gov/protein/CAA71948) -> [HBX2855210](http://www.ncbi.nlm.nih.gov/protein/HBX2855210)
* [SHV-19](http://www.ncbi.nlm.nih.gov/pubmed/11120950): [AAF34333](http://www.ncbi.nlm.nih.gov/protein/AAF34333) -> [HBU8935839](http://www.ncbi.nlm.nih.gov/protein/HBU8935839)
* [SHV-84](http://www.ncbi.nlm.nih.gov/pubmed/20211886): [CAJ32371](http://www.ncbi.nlm.nih.gov/protein/CAJ32371) -> [HBU8836957](http://www.ncbi.nlm.nih.gov/protein/HBU8836957)

Thanks,
Bogdan

**Comment by danielhhaft** [comment]
Thanks, Bogdan,

I've made the changes for the three SHV alleles.  The partials were very
close to full length, so, it seemed a very non-controversial move to make.
Thank you for alerting me.

Dan Haft

**Comment by iorga** [comment]
Many thanks @danielhhaft for processing the sequences so quickly !

**Comment by bpalcock** [comment]
Thanks Bogdan, these have been updated in CARD as well for the next release
