### ISSUE TITLE
possible mis-annotation in protein homolog model entry?

### ISSUE THREAD

**Issue by Pauldenny** [arpcard/amr_curation#104]
<html>
<body>

Accession | ARO:3002272
-- | --
CARD Short Name | VIM-2

</body>
</html>
https://card.mcmaster.ca/ontology/38672

Shows PMID 18804966 (http://www.ncbi.nlm.nih.gov/pubmed/18804966)) as relevant literature - but on skimming this paper, I can I only find mention of VIM-11, but not VIM-2.
Cheers, Paul

**Comment by bpalcock** [comment]
Thanks for bringing this to our attention Paul, I've updated the PMID to 10722487. This will be included in the next release next month.
Cheers,
Brian
