### ISSUE TITLE
To find Antimicrobial resistance and susceptibility from CARD

### ISSUE THREAD

**Issue by Javeria-12** [arpcard/amr_curation#108]
how do I check AMR  from CARD using SRA NCBI data??
I got genbank assession number of SRA NCBI isolates from nucleotide  when I enter this assession number on card search it show me an error while BV-BRC give me results of AMR now I want to check AMR sing CARD database

**Comment by raphenya** [comment]
@Javeria-12 You can use CARD’s RGI software to predict AMR genes from nucleotides or protein sequences. The RGI software is available via the website at https://soho.mcmaster.ca/analyze/rgi and the command line version at https://github.com/arpcard/rgi.
