### ISSUE TITLE
3 duplicate sequences

### ISSUE THREAD

**Issue by tseemann** [arpcard/amr_curation#11]
```
WARNING: duplicate 624 bp sequence: catP ~  catD

WARNING: duplicate 654 bp sequence: Proteus_mirabilis_chloramphenicol_acetyltransferase ~  catA4

WARNING: duplicate 1152 bp sequence: ADC-22 ~  ADC-80
```

**Comment by agmcarthur** [comment]
Thanks @tseemann, I'll look to see why our QC scripts missed these and will get them fixed shortly.

**Comment by arpcard** [comment]
Will be addressed in August 2019 patch release.

**Comment by tseemann** [comment]
I am glad this github project exists now, it means things like this won't get lost anymore.

**Comment by arpcard** [comment]
@tseemann these were fixed, but 5 more slipped through. I found the gap in the QC code and fixed it so this will stop happening. Duplicates in CARD 3.0.4 (released today):

duplicate protein sequence: [Shigella flexneri chloramphenicol acetyltransferase] [catI]
duplicate protein sequence: [mexR] [mexR]
duplicate protein sequence: [Type B NfxB] [Type A NfxB]
duplicate protein sequence: [OXA-135] [OXA-151]
duplicate protein sequence: [MIR-5] [MIR-8]

**Comment by tseemann** [comment]
Duplicate protein is not a problem?
As long as the underlying DNA (CDS) sequence is different?
Different allelles with synonymous mutations can be expressed differently!

**Comment by tseemann** [comment]
See #18 now.
