### ISSUE TITLE
ARO:3003967 lrfA should be lfrA, plus other fixes.

### ISSUE THREAD

**Issue by danielhhaft** [arpcard/amr_curation#13]
ARO:3003967 lrfA should be lfrA

Written description should cite only PMID:8682782, not PMID:10874120.

Written description should drop all mention of Pseudomonas.

**Comment by arpcard** [comment]
Will be addressed in August 2019 patch release.

**Comment by arpcard** [comment]
Corrected: https://card.mcmaster.ca/ontology/40738
