### ISSUE TITLE
ARO:3004138 not just gene

### ISSUE THREAD

**Issue by fmaguire** [arpcard/amr_curation#15]
In the latest release 3.0.3 the nucleotide sequence for ARO:3004138 is 1.8MB and looks like it might accidentally be the full [_Moraxella_ genome](https://www.ncbi.nlm.nih.gov/nuccore/CP002005) instead of just the 23S.

**Comment by fmaguire** [comment]
Looks like people using the CARD data have also run into this problem: https://github.com/sanger-pathogens/ariba/issues/278

**Comment by arpcard** [comment]
We're aware of this and working on a fix that should be released imminently

**Comment by arpcard** [comment]
Fixed: https://card.mcmaster.ca/ontology/41265
