### ISSUE TITLE
penem vs penam

### ISSUE THREAD

**Issue by tseemann** [arpcard/amr_curation#23]
aro_category_name  / "Drug Class"
```
  # frequency in card.json
    314 penem
   1404 penam
```
Are these synonyms?

**Comment by arpcard** [comment]
No, they are different structures:

Penams, often referred to as penicillins, are a group of antibiotics derived from _Penicillium_ fungi. https://card.mcmaster.ca/ontology/36017

Penems are a class of unsaturated beta-lactam antibiotics with a broad spectrum of antibacterial activity and have a structure which renders them highly resistant to beta-lactamases. All penems are all synthetically made. There are only two listed in CARD: faropenem & ticarcillin.
https://card.mcmaster.ca/ontology/40360
