### ISSUE TITLE
17 named ARGs without a Drug Class annotation

### ISSUE THREAD

**Issue by tseemann** [arpcard/amr_curation#24]
The following entries don't have a "Drug Class" annotation.
eg `BAT-1 is a class D beta-lactamase found in Bacillus atrophae
us.`
Should they?
All other 2500 genes do.

```

BAT-1   AJRJ01000061.1:17604-18411
BCL-1   EF540343.1:3313-4237
BES-1   AF234999.1:190-1069
BIC-1   GQ260093.1:1-886
BIL-1   X74512.1:127-1273
BKC-1   KP689347.1:8603-9545
CBP-1   KP718480.1:1-928
CGA-1   AF339733.1:437-1316
CKO-1   AF477396.1:1-904
CME-1   AJ006275.1:72-960
CMH-1   JQ673557.1:1-1147
DES-1   AF426161.1:119-1094
ERP-1   AY077733.1:1-883
FAR-1   AF024601.1:303-1197
FIM-1   JX570731.1:1937-2726
FPH-1   CP010019.1:78319-79186
FTU-1   CP001633.1:630304-631168
```

**Comment by arpcard** [comment]
they show up as having a drug class on the website so I'm not sure what's going on here, let me know if the error persists after the next release

**Comment by tseemann** [comment]
I can confirm that this is fixed in the latest version of CARD. 
Thank you.
