### ISSUE TITLE
add complete sequence for SHV-4 beta-lactamase

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#26]
Hello,

Only a partial sequence used to be available for the SHV-4 beta-lactamase: https://www.ncbi.nlm.nih.gov/protein/P37323

Recently, a complete sequence of SHV-4 was submitted to NCBI with the name "SHV-3". I've contacted the authors and they made the necessary correction. The complete protein and nucleotide sequences can be found now at https://www.ncbi.nlm.nih.gov/protein/SPD96731 and https://www.ncbi.nlm.nih.gov/nuccore/LT985229.1?from=36108&to=36968, respectively, with the correct name.

Could you please add this new sequence to CARD? Thank you in advance.

Bogdan

**Comment by arpcard** [comment]
Hi Bogdan, the SHV-4 term in CARD has been updated for the next release
