### ISSUE TITLE
complete sequence for LEN-12 beta-lactamase

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#28]
A complete sequence is available now for LEN-12 beta-lactamase ([PXK69226](https://www.ncbi.nlm.nih.gov/protein/PXK69226)), which should replace the old, partial one ([CAG25817](https://www.ncbi.nlm.nih.gov/protein/CAG25817)).

**Comment by arpcard** [comment]
thanks Bogdan, I've updated the sequence for release
