### ISSUE TITLE
ACI-1 includes more drug classes than parent term ACI beta-lactamase

### ISSUE THREAD

**Issue by chris-rands** [arpcard/amr_curation#3]
In @arpcard [ACI-1 ](https://card.mcmaster.ca/ontology/41531) includes drug classes "penam, cephalosporin" but [ACI beta-lactamase](https://card.mcmaster.ca/ontology/41530) (the parental term) includes only "cephalosporin". I think the parental family should perhaps include both drug classes too.

Also, the ACI-1 entry parent terms includes "confers_resistance_to_drug" to amoxicillin and cefotaxime. However, the [original paper ](https://www.ncbi.nlm.nih.gov/pubmed/11036038) reports resistance to "penicillins (penicillin, amoxicillin, and ticarcillin)" and "expanded-spectrum cephalosporins (cefotaxime and ceftazidime)", so perhaps additional terms would be useful here also, if I understand this correctly.

Thank you for considering this, Chris

**Comment by arpcard** [comment]
Thanks Chris, this term has been updated for the next release!
