### ISSUE TITLE
NCBI feedback on CARD-3.0.5

### ISSUE THREAD

**Issue by danielhhaft** [arpcard/amr_curation#32]
CAA90890.1    blaBRO-1           One amino acid too long, please replace with AAA92126.1. Better RBS positioning, etc.

AIG20028.1      AZECL-25         AZECL series designations appear only in one article, only in supplemental materials. CARD please do not use. AZECL-1 = blaACT-17, AZECL-14 = blaACT-15, AZECL-5 = blaMIR-3, AZECL-41 = blaACT-23, etc.   NCBI is making AZECL-25 into blaMIR-23.   NCBI has sent email requests to both corresponding authors, and hopes to make proper assignments and get consent to revise the currrent GenBank records.

NCBI endorses blaLEN-35, blaLEN-36, blaLEN-37

and was able to match these additional ones from Pasteur's definition to public sequences:

blaLEN_30 gi|1172578505|ref|WP_080923375 SLY33602.1
blaLEN_32 gi|762039390|ref|WP_043875313 CEL85185.1
blaLEN_34 gi|1115553591|ref|WP_072124806 CTQ12020.1
blaLEN_38 gi|1621035936|ref|WP_136086342 AZA07954.1
blaLEN_39 gi|1620969597|ref|WP_136026639 AZA07955.1
blaLEN_40 gi|1620995168|ref|WP_136049560 AZA07956.1
blaLEN_41 gi|1293416693|ref|WP_100675621 AZA07958.1
blaLEN_42 gi|1000903631|ref|WP_061154665 AZA07959.1
blaLEN_43 gi|1123848914|ref|WP_074385924 AZA07957.1
blaLEN_51 gi|1520296400|ref|WP_123836928 AYW19907.1
blaLEN_55 gi|1236116734|ref|WP_094917017 OZM21578.1
blaLEN_58 gi|1468079365|ref|WP_117122976 SXE97430.1

NCBI hopes to publish NG records for these in a few days.

**Comment by arpcard** [comment]
`CAA90890.1 blaBRO-1 One amino acid too long, please replace with AAA92126.1. Better RBS positioning, etc.`
- replaced with AAA92126.1

`AIG20028.1 AZECL-25 AZECL series designations appear only in one article, only in supplemental materials. CARD please do not use. AZECL-1 = blaACT-17, AZECL-14 = blaACT-15, AZECL-5 = blaMIR-3, AZECL-41 = blaACT-23, etc. NCBI is making AZECL-25 into blaMIR-23. NCBI has sent email requests to both corresponding authors, and hopes to make proper assignments and get consent to revise the currrent GenBank records.`
- I've renamed AZECL-25 to MIR-23 and moved it under the blaMIR family, but I've left AZECL-25 as a synonym until this change has been approved and formalized. I have also removed the CARD AMR Gene Family blaAZECL. I will also double-check that we have these other beta-lactamases in CARD.

> NCBI endorses blaLEN-35, blaLEN-36, blaLEN-37
> 
> and was able to match these additional ones from Pasteur's definition to public sequences:
> 
> blaLEN_30 gi|1172578505|ref|WP_080923375 SLY33602.1
> blaLEN_32 gi|762039390|ref|WP_043875313 CEL85185.1
> blaLEN_34 gi|1115553591|ref|WP_072124806 CTQ12020.1
> blaLEN_38 gi|1621035936|ref|WP_136086342 AZA07954.1
> blaLEN_39 gi|1620969597|ref|WP_136026639 AZA07955.1
> blaLEN_40 gi|1620995168|ref|WP_136049560 AZA07956.1
> blaLEN_41 gi|1293416693|ref|WP_100675621 AZA07958.1
> blaLEN_42 gi|1000903631|ref|WP_061154665 AZA07959.1
> blaLEN_43 gi|1123848914|ref|WP_074385924 AZA07957.1
> blaLEN_51 gi|1520296400|ref|WP_123836928 AYW19907.1
> blaLEN_55 gi|1236116734|ref|WP_094917017 OZM21578.1
> blaLEN_58 gi|1468079365|ref|WP_117122976 SXE97430.1
> 
> NCBI hopes to publish NG records for these in a few days.

- we will also add these to our records

**Comment by arpcard** [comment]
Issue resolved with today's release of CARD 3.0.7:

BRO-1
AZECL-25 (now MIR-23)
LEN-30
LEN-32
LEN-34
LEN-38
LEN-39
LEN-40
LEN-41
LEN-42
LEN-43
LEN-51
LEN-55
LEN-58
