### ISSUE TITLE
CMY-136 beta-lactamase

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#35]
Hi,

Could you please add the CMY-136 beta-lactamase (CMY-2-like)?

GenBank [AVR61040](https://www.ncbi.nlm.nih.gov/protein/AVR61040.1), published in [ACS Infect Dis 2019](https://doi.org/10.1021/acsinfecdis.8b00240) (I can provide the pdf if needed ;-))

Thanks,
Bogdan

**Comment by arpcard** [comment]
Hi Bogdan, we've added this gene for availability with the next release. Thanks for bringing it to our attention!
