### ISSUE TITLE
allele number for OXA-258b

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#36]
In [Papalia et al 2013](https://doi.org/10.1128/JCM.03043-12) there are two OXA-258 enzymes described, named as OXA-258a and OXA-258b, with sequences submitted as [CCE73593](https://www.ncbi.nlm.nih.gov/protein/452084995) and [CCP19563](https://www.ncbi.nlm.nih.gov/protein/480352515), respectively. These enzymes were further characterized in [Papalia et al 2018](https://doi.org/10.1016/j.jgar.2018.03.015).

The first enzyme is present in our databases as OXA-258, and the second one is not. Should we include it as OXA-258b, or give it a new allele number? Personally I would prefer the second option, and putting OXA-258b as a synonym.

Thanks,
Bogdan

**Comment by tseemann** [comment]
```
>CCE73593.2 betalactamase OXA258 variant [Achromobacter ruhlandii]
MTVRLVSRALGAVLFASALTLPARADVLCTLVADAADGRILFQQGTRQDCTQRYTPASTFKLPIALMGAD
AGILQGPHQPVWNYQPAYPDWGGEAWRQPTDPARWIKYSVVWYSQLTARALGQERFQRYTSAFGYGNADV
SGEPGKHNGTDGAWIISSLRISPFEQVDFLRKFVNRQLPVKAAAYDLAENLFEVGEADGWRLYGKTGTGS
PGSHGVYTPANAYGWFVGWARKDDRQLVFARLLQDEGATQPNAGLRARDGLMRDWAAMVAAPRK


>CCP19563.2 betalactamase new OXA variant [Achromobacter ruhlandii]
MTVRLVSRALGAVLFASALTLPARADVLCTLVADAADGRILFQQGTRQDCTQRYTPASTFKLPIALMGAD
AGILQGPHQPVWNYQPAYPDWGGEAWRQPTDPARWIKYSVVWYSQLTARALGQERFQRYTSAFGYGNADV
SGEPGKHNGTDGAWIISSLHISPFEQVDFLRKFVNRQLPVKAAAYDLAENLFEVGEADGWRLYGKTGTGS
PGSHGVYTPANAYGWFVGWARKDDRQLVFARLLQDEGATQPNAGLRARDGLMRDWAAMVAAPRK
```

**Comment by arpcard** [comment]
we'll reach out to NCBI about this as we do not decide allele numbers/names for new beta-lactamases

**Comment by danielhhaft** [comment]
blaOXA-925 is assigned. OXA-258b is a synonym. Thanks to CARD and to Bogdan Iorga.

**Comment by iorga** [comment]
Thank you @arpcard and @danielhhaft . Close #36 .
