### ISSUE TITLE
RTG-1 beta-lactamase incorrectly assigned as a synonym of CARB-12

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#38]
On the Lahey website, RTG-1 used to be a synonym of CARB-12, with the accession number [D13210](https://www.ncbi.nlm.nih.gov/nuccore/D13210) for nucleotide sequence and [BAA02497](https://www.ncbi.nlm.nih.gov/protein/BAA02497) for the protein sequence. This information is present now also in [CARD](https://card.mcmaster.ca/ontology/38650). In NCBI AMRDB, the corresponding CARB-12 sequence ([WP_063857839](https://www.ncbi.nlm.nih.gov/protein/WP_063857839)) is assigned to the PSE-like (CARB-1-like) family of beta-lactamases, which is correct.
```
>WP_063857839.1 MULTISPECIES: PSE family carbenicillin-hydrolyzing class A beta-lactamase CARB-12 [Gammaproteobacteria]
MKFLLVFSLLIPSVVFASSSKFRQVEQDVKAIEVSLSARIGVSVLDTQNGEYWDYNGNQRFPLTSTFKTI
ACAKLLYDAEQGKVNPNSTVEIKKADLVTYSPVIEKQVGQAITLDDACFATMTTSDNTAANIILSAVGGS
KGVTDFLRQIGDKETRLDRIEPDLNEGKLGDLRDTTTPKAIASTLNKFLFGSALSEMNKKKLESWMVNNQ
VTGNLLRSVLPAGWNIADRSGAGGFGARSITAVVWSEHQAPIIVSIYLAQTQASMAERNDAIVKIGRSIF
DVYTSQSR
```

RTG-1 was originally reported in 1991 from the strain _Proteus mirabilis_ GN79 ([PubMed](https://www.ncbi.nlm.nih.gov/pubmed/?term=1840585), [DOI](https://doi.org/10.1128/jb.173.21.7038-7041.1991)). Among other citations, RTG-1 is referred to in the [RTG-4 paper](https://doi.org/10.1128/AAC.01164-08). The nucleotide sequence of RTG-1 is [D13209](https://www.ncbi.nlm.nih.gov/nuccore/D13209.1?from=312&to=1208) and the protein sequence is [BAA02496](https://www.ncbi.nlm.nih.gov/protein/BAA02496.1). It belongs to the RTG-like (CARB-5-like) family and is not present in NCBI AMRDB or in CARD.

```
>BAA02496.1 beta-lactamase precursor [Proteus mirabilis]
MNVRQHKASFFSVVITFLCLTLSLNANATDSVLEAVTNAETELGARIGLAAHDLETGKRWEHKSNERFPL
SSTFKTLACANVLQRVDLGKERIDRVVRFSESNLVTYSPVTEKHVGKKGMSLAELCQATLSTSDNSAANF
ILQAIGGPKALTKFLRSIGDDTTRLDRWEPELNEAVPGDKRDTTTPIAMVTTLEKLLIDETLSIKSRQQL
ESWLKGNEVGDALFRKGVPSDWIVADRTGAGGYGSRAITAVMWPPNRKPIVAALYITETDASFEERNAVI
AKIGEQIAKTVLMENSRN
```
I would suggest:
1. Assign a CARB allele number for the RTG-1 sequence.
2. Change in CARD the RTG-1 synonym from CARB-12 to this new CARB.

**Comment by arpcard** [comment]
We'll remove RTG-1 as a synonym of CARB-12 and reach out to NCBI about assigning a CARB allele number for RTG-1

**Comment by danielhhaft** [comment]
NCBI here. Good example of when to make a 3rd party request for an allele assignment by NCBI.  I agree an allele assignment is needed.

blaCARB-54  is the new designation for BAA02496.1

Dan Haft

**Comment by iorga** [comment]
Thank you @arpcard and @danielhhaft . Close #38 .
