### ISSUE TITLE
Assign a CARB allele number to WP_071846358

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#39]
The sequence [WP_071846358](https://www.ncbi.nlm.nih.gov/protein/WP_071846358.1) is present in NCBI AMRDB, but not in CARD. It was added to NCBI AMRDB in the period 16-18 January 2017 as a PSE-like (CARB-1-like) beta-lactamase, but without providing a CARB allele number.

```
>WP_071846358.1 PSE family carbenicillin-hydrolyzing class A beta-lactamase [Salmonella enterica]
MKFLWAFSHLIPSVVFASSSKFQQVEQDVKAIEVSLSARIGVSVYDTQNGEYWDYNGNQRFPLTSTFKTI
ACAKLLYDAEQGKVNPNSTVEIKKADLVTYSPVIEKQVGQAITLDDACFATMTTSDNTAANIILSAVGGP
KGVTDFLRQIGDKETRLDRIEPDLNEGKLGDLRDTTTPKAIASTLNKFLFGSALSEMNQKKLESWMVNNQ
VTGNLLRSVLPAGWNIADRSGAGGFGARSITAVVWSEHQAPIIVSIYLAQTQASMAERNDAIVKIGHSIF
DVYTSQSR
```

It would be useful if a CARB allele number could be assigned for this sequence, and then add it to CARD.

**Comment by danielhhaft** [comment]
NCBI agrees.
WP_071846358.1 is now allele  blaCARB-55

PSE family carbenicillin-hydrolyzing class A beta-lactamase CARB-55

It may be a couple of weeks before the revised annotation is visible publicly in NCBI resources.
