### ISSUE TITLE
qnrE family of plasmid-mediated quinolone resistance protein is missing

### ISSUE THREAD

**Issue by sauralph** [arpcard/amr_curation#4]
I have noticed that qnrE family is missing from the CARD database. It is however registered on the NCBI website [here](https://www.ncbi.nlm.nih.gov/pathogens/isolates#/refgene/gene_family:(qnrE))

Is this family under review or is it an omission?

**Comment by arpcard** [comment]
This was an accidental omission and it will be updated for the next release.
