### ISSUE TITLE
Very basic question about resistance SNPs

### ISSUE THREAD

**Issue by smarini** [arpcard/amr_curation#41]
I have a very basic question on how CARD resistant mutations are annotated.

Let's take for example the protein here: [https://card.mcmaster.ca/ontology/40507](https://card.mcmaster.ca/ontology/40507)

The nonsynonimous amino acid variants listed in green are: G81C S83L. I would expect to find therefore either G or C in position 81, and S or L in position 83. However, we see in position 81 and 83 a S and a V, respectively.

I  read that S81 and V83 are "discovered via laboratory selection experiments" (red color), while G81C and S83L are present in "clinical, agricultural, or environmental isolates" (green color).

I am not sure about how to interpret this--which are the WT and the mutated amino acids to consider?

**Comment by arpcard** [comment]
Hi Simone, thanks for bringing this to our attention.

What's happened here is the publication gives the AMR mutations as G81C and S83L but is using the E. coli gyrA numbering. If you look at the sequence you've sent, the bases we're actually interested in are G79 and S81. I've gone ahead and corrected these, they should be available to you with the next public release.

As for the "discovered via lab selection" colors, just to avoid confusion those only apply to the colored boxes around the amino acid variants - green for clinical, orange for lab selection - in the sequence itself they always appear as red letters.

Hope this helps.

**Comment by smarini** [comment]
Thanks a lot!

Actually, there are several of these "non corresponding" variants, I'll look closer into it and come up with a list for the next release.

**Comment by smarini** [comment]
For future releases, I attach here a list of protein variants that do not correspond to the reported proteins. Thanks again for the support!
[aa.variants.missing.correspondence.csv.tar.gz](https://github.com/arpcard/amr_curation/files/4258465/aa.variants.missing.correspondence.csv.tar.gz)
