### ISSUE TITLE
Neisseria gonorrhoeae folP 

### ISSUE THREAD

**Issue by amoreming** [arpcard/amr_curation#42]
Hi, 
I’m writing because in the article referenced for the Neisseria gonorrhoeae folP with mutation conferring resistance to sulfonamides (PMID 31358980) the mutation mentioned is folP R228S and in RGI and database appears as R229S.

Don’t know if this could have been an error. 
Thanks for the clarification
Albert

**Comment by huynhw1** [comment]
Hey there @amoreming!

Thanks for pointing this out. The referenced article does indeed say R228S. I've fixed the mutation mentioned from R229S to R228S.

Sincerely,
William
