### ISSUE TITLE
ARO:3003103 incorrect gene name?

### ISSUE THREAD

**Issue by marlam89** [arpcard/amr_curation#44]
ARO:3003103 labelled as 'cphA7' in CARD but matches to 'cphA1' in NCBI and Betalactamase Database (bldb) at both the nucleotide and amino acid sequences.

**Comment by danielhhaft** [comment]
At NCBI, in the cphA family, the following families are designated "allele", meaning only one unique full-length sequence is allowed:
cphA2. cphA3, cphA4, cphA5, cphA6, cphA7, cphA8, imiH, imiS.

The only node that is a child of cphA, and not designated allele, is cphA1.  That node contains five different non-identical sequences, and those five are not particularly close to each other, as opposed to being closer to other alleles.  The cphA family's nomenclature is not administered by NCBI, but instead represents an attempt to mirror usages seen elsewhere.

It might be appropriate to make some change to the nomenclature of current cphA1 proteins.
