### ISSUE TITLE
a confusion about  drug class and antibiotic in card.json

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#49]
hi @arpcard 
    some models in card.json have  both drug class and antibiotic at, and antibioc is a drug of the drug  class（for example model 2：Cephaloridine is a cephalosporin），some others only have drug class （for example model 7).
Does it mean that model 7 is no ablity to resistance to  Cephaloridine ？How should I understand it?

**Comment by huynhw1** [comment]
Hey there @feihongloveworld ,
The Curation of individual drugs are not complete; the curation of drug classes are given priority.

Thanks.
--------
William Huynh, CARD Curator-Developer
