### ISSUE TITLE
ANT(3'')-IIc only resistence to to streptomycin and spectinomycin but did not result in increased resistance to other aminoglycosides

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#50]
hi sir：
    the paper of ANT(3'')-IIc description as below：
’‘’
All of the above candidate genes increased the resistance of E. coli to streptomycin and spectinomycin by 32–128-fold, compared to the control (E. coli harboring the null vector pUC18 only) (Table 1). However, the expressed ANTs did not result in increased resistance to other aminoglycosides, suggesting a substrate specificity for the transferase, consistent with other enzymes of the ANT(3") class
‘’‘  
its mean than ANT(3'')-IIc only resistence to  streptomycin and spectinomycin not aminoglycosides antibiotic class.
Inaccurate description in carddatabase maybe.
thanks.

**Comment by arpcard** [comment]
Streptomycin and Spectinomycin are aminoglycosides.
So ANT(3") does confer resistance to aminoglycosides. However, as the paper suggests, it is more specific towards Streptomycin and Spectinomycin compared to other aminoglycosides.

As mentioned in a previous issue, resistance to individual drugs are incomplete on CARD, so Drug Class is prioritized.

**Comment by feihongloveworld** [comment]
hi sir：
      When will the new version of the database and rig soft be released ？ 
     I look forward to it .
thanks
