### ISSUE TITLE
allele numbers in ROB beta-lactamase family

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#53]
Hello,

The opening of this issue was prompted by the publication of a recent paper, [Kadlec et al JAC 2019](https://doi.org/10.1093/jac/dky515), reporting a new beta-lactamase that was named ROB-2 (GenBank: [AWU47610.1](https://www.ncbi.nlm.nih.gov/protein/AWU47610.1) ; [MH316128.1](https://www.ncbi.nlm.nih.gov/nuccore/MH316128.1)). This name conflicts with the existing allele numbers in this family, as I will show below.

Currently, at **NCBI** there are 5 ROB beta-lactamases, from ROB-1 to ROB-5. A paper is available only for ROB-1, [Chang et al Vet Microbiol 1992](http://dx.doi.org/10.1016/0378-1135(92)90154-L).

allele | refseq_protein_accession | refseq_nucleotide_accession
-- | -- | --
blaROB-1 | WP_005618523.1 | NG_049977.1
blaROB-2 | WP_015431537.1 | NG_059321.1
blaROB-3 | WP_075606311.1 | NG_059331.1
blaROB-4 | WP_078318620.1 | NG_059330.1
blaROB-5 | WP_103034696.1 | NG_059337.1

At **CARD**, only ROB-1 is present, which is in agreement with their policy to incorporate only sequences described in a paper.

In GenBank/RefSeq there are some other ROB beta-lactamases without assigned allele numbers:
- three new sequences described in [Clemente et al Sci Adv 2015](http://dx.doi.org/10.1126/sciadv.1500183) (see page 12 of Supplementary Material file): [AIW80558](https://www.ncbi.nlm.nih.gov/protein/AIW80558) ; [AIW80572](https://www.ncbi.nlm.nih.gov/protein/AIW80572) ; [AIW80573](https://www.ncbi.nlm.nih.gov/protein/AIW80573)
- the sequence mentioned at the beginning of this message, published in [Kadlec et al JAC 2019](https://doi.org/10.1093/jac/dky515): [AWU47610.1](https://www.ncbi.nlm.nih.gov/protein/AWU47610.1)
- a sequence that has no associated paper yet: [MWQ02887](https://www.ncbi.nlm.nih.gov/protein/MWQ02887)

All these sequences have >99 % sequence identity with ROB-1.

I would suggest to:
- assign ROB-6 to ROB-8 to the  three new sequences described in [Clemente et al Sci Adv 2015](http://dx.doi.org/10.1126/sciadv.1500183)
- assign ROB-9 to the sequence from [Kadlec et al JAC 2019](https://doi.org/10.1093/jac/dky515)
- ideally assign ROB-10 to the sequence [MWQ02887](https://www.ncbi.nlm.nih.gov/protein/MWQ02887), although I know that this is not part of NCBI's policy

Thank you in advance. Best regards,
Bogdan

**Comment by iorga** [comment]
And here is the alignment of all these protein sequences:

```
AAB24384.1|ROB-1|       MLNKLKIGTLLLL--TLTACSPNSVHSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
AGH37381.1|ROB-2|       MFNKLKIGTLLLL--TLTACSLNSVHSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
OOS23853.1|ROB-3|       MLNKLKIGTLLLLTLTLTACSPNSVHSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
OOS22656.1|ROB-4|       MLNKLKIGTLLLLTLTLTACSPNSVHSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
PNP96721.1|ROB-5|       MFNKLKIGTLLLL--TLTACSPNSVHSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
AIW80558.1|ROB-T1|      MLNKLKIGTLLLL--TLTACLPNFVHSVTSNPQPASAPVQQSATQATFQQTSANLEQQYQ
AIW80572.1|ROB-T2|      MLNKLKIGTLLLL--TLTACLPNSVLSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
AIW80573.1|ROB-T3|      MLNKLKIGTLLLL--TLTACLPNSVPSVTSNPQPASAPVQQSATQATFQQTSANLEQQYQ
AWU47610.1|ROB-T4|      MLNKLKIGTLLLL--TLTACSPNSVHSVKSNPQPASAPVQQSATQATFQQTLANLEQQYQ
MWQ02887.1|ROB-T5|      MFNKLKIGTLLLL--TLTACSPNSVHSVTSNPQPASAPVQQSATQATFQQTLANLEQQYQ
                        *:***********  *****  * * **.********************** ********

AAB24384.1|ROB-1|       ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
AGH37381.1|ROB-2|       ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
OOS23853.1|ROB-3|       ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
OOS22656.1|ROB-4|       ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
PNP96721.1|ROB-5|       ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
AIW80558.1|ROB-T1|      ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
AIW80572.1|ROB-T2|      ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
AIW80573.1|ROB-T3|      ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
AWU47610.1|ROB-T4|      ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
MWQ02887.1|ROB-T5|      ARIGVYVWDTETGHSLSYRADERFAYASTFKALLAGAVLQSLPEKDLNRTISYSQKDLVS
                        ************************************************************

AAB24384.1|ROB-1|       YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHTNR
AGH37381.1|ROB-2|       YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHTNR
OOS23853.1|ROB-3|       YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHANR
OOS22656.1|ROB-4|       YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHANR
PNP96721.1|ROB-5|       YSPETQKYVGKGMTIAQLCEAAVRFSDNTATNLLLKELGGVEQYQRILRQLGDNVTHANR
AIW80558.1|ROB-T1|      YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHTNR
AIW80572.1|ROB-T2|      YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHTNR
AIW80573.1|ROB-T3|      YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHTNR
AWU47610.1|ROB-T4|      YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHANR
MWQ02887.1|ROB-T5|      YSPETQKYVGKGMTIAQLCEAAVRFSDNSATNLLLKELGGVEQYQRILRQLGDNVTHANR
                        ****************************:****************************:**

AAB24384.1|ROB-1|       LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
AGH37381.1|ROB-2|       LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
OOS23853.1|ROB-3|       LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
OOS22656.1|ROB-4|       LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
PNP96721.1|ROB-5|       LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
AIW80558.1|ROB-T1|      LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
AIW80572.1|ROB-T2|      LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
AIW80573.1|ROB-T3|      LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
AWU47610.1|ROB-T4|      LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
MWQ02887.1|ROB-T5|      LEPDLNQAKPNDIRDTSTPKQMAMNLNAYLLGNTLTESQKTILWNWLDNNATGNPLIRAA
                        ************************************************************

AAB24384.1|ROB-1|       TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
AGH37381.1|ROB-2|       TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
OOS23853.1|ROB-3|       TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
OOS22656.1|ROB-4|       TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDTAKQ
PNP96721.1|ROB-5|       TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
AIW80558.1|ROB-T1|      TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
AIW80572.1|ROB-T2|      TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
AIW80573.1|ROB-T3|      TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
AWU47610.1|ROB-T4|      TPTSWKVYDKSGAGKKYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
MWQ02887.1|ROB-T5|      TPTSWKVYDKSGAG-KYGVRNDIAVVRIPNRKPIVMAIMSTQFTEEAKFNNKLVEDAAKQ
                        ************** *****************************************:***

AAB24384.1|ROB-1|       VFHTLQLN
AGH37381.1|ROB-2|       VFHTLQLN
OOS23853.1|ROB-3|       VFHTLQLN
OOS22656.1|ROB-4|       VFHTLQLN
PNP96721.1|ROB-5|       VFHTLQLN
AIW80558.1|ROB-T1|      VFHTLQLN
AIW80572.1|ROB-T2|      VFHTLQLN
AIW80573.1|ROB-T3|      VFHTLQLN
AWU47610.1|ROB-T4|      VFHTLQLN
MWQ02887.1|ROB-T5|      VFHTLQLN
                        ********
```

**Comment by huynhw1** [comment]
Hello @iorga ,

ROB-6 to ROB-10 have been added to CARD as per your suggestions.

Thank you.

**Comment by danielhhaft** [comment]
ROB-6 to ROB-10 have been added to NCBI as well.

Please note that NCBI lists ROB among the families for which submitters can request an allele assignment. Such families include all that Lahey covered, plus ADC and PDC, for which there was high demand, plus several that were Lahey-style, as is, mobilized and clinically significant. In a number of cases, these authors describing the first allele have invited NCBI to curate future alleles.

Allele reservations are useful to protect manuscripts in preparation from nomenclature collisions or changes. In the case of blaROB, there happened to be no processed but unreleased ROB proteins, awaiting release upon publication.   But because novel alleles may be HUP (Hold Until Publication), bypassing NCBI to make up allele names creates dangers to users, submitters, authors working to publish, etc.  It is also a danger if CARD makes beta-lactamase assignments independent of NCBI's allele reservation system, even if there are no help sequences, because just as much damage can be done if we are unaware the assignment was made.  

NCBI does support 3rd party allele requests for families we cover, when it seems justified by mobility of the gene, clinical relevance, and perhaps active efforts to prepare review articles on specific families.   We would like to discourage work assigning alleles in cases that can result in nomenclature collisions, especially for families that NCBI covers.  So please do not attempt independent allele assignments for such families, since the danger that this can lead to nomenclature collisions and confusion is very great.

**Comment by iorga** [comment]
Thank you @arpcard and @danielhhaft .
