### ISSUE TITLE
load aac(3)-IIg, block aac(3)-IIf

### ISSUE THREAD

**Issue by danielhhaft** [arpcard/amr_curation#54]
This issue arises from a discussion between Sally Partridge and NCBI, at the behest of Partridge, and reports addition of a new AME by NCBI to the AMRFinder database.

In a review article from FEMS Microbiol Rev. in 2011, PMID:21564142, "Analysis of antibiotic resistance regions in Gram-negative bacteria",  Partridge identified protein CAJ29624.1 as a novel aac(3)-II and suggested the term "aac(3)-IIf".  This suggestion did not make it into most public AMR databases. NCBI carried this protein as simply aac(3)-II.
 
More recently, Costello, et al. PMID: 30389638 (2019) used the term "aac(3)-IIf" to refer to newly sequence protein AOZ57694.1, but that protein is nearly identical in sequences to sequences broadly accepted as aac(3)-IIe.  NCBI and Sally Partridge concur that AOZ57694.1 should be considered part of the aac(3)-IIe family.  For those who wish to refer to a protein with an exact amino acid sequence, analogous to what is done with beta-lactamase alleles, we recommend use of a protein accession number.
 
Now, PMID: 32571822  (Antimicrob Agents Chemother . online ahead of print, 2020 Jun 22) uses the name aac(3)-IIg in its title for QKT21444.1. Identical proteins include CAJ29624.1 for which Partridge had in 2011 suggested the name "aac(3)-IIf"
  
Because "aac(3)-IIf" has been used twice in the literature with two different meanings, neither one well-established, and "aac(3)-IIg" appears in an article title already available in PubMed based on a pre-publication on-line version, NCBI suggests using "aac(3)-IIg" as the name for this family, and keeping "aac(3)-IIf" unused. Dr. Partridge agrees with
this proposal.  This GitHub ticket is proposed to serve as a public record of the nomenclature resolution for the terms "aac(3)-IIf" and "aac(3)-IIg".
 
The annotation for CAJ29624.1, currently aac(3)-II, will change to aac(3)-IIg the next time NCBI's AMR database is updated. We hope (the) CARD will concur.

**Comment by huynhw1** [comment]
Hey @danielhhaft ,

I've added AAC(3)-IIg in CARD using the paper and the accession mentioned.

Thanks for letting us know!
