### ISSUE TITLE
tetracenomycin C does not appear in ontology

### ISSUE THREAD

**Issue by ctSkennerton** [arpcard/amr_curation#55]
While doing some data linking I noticed that tetracenomycin C isn't in the ontology. The only reference to it was in ARO:3003554, which is the part of the efflux system for it.

**Comment by huynhw1** [comment]
Hello @ctSkennerton ,

Going back to some of our notes, we have previously (2 years ago) determined that Tetracenomycin should be excluded form CARD as it is an anti-tumour drug.

However, I am doing some initial research now and I see novel papers describing antibiotic activity. As such I will consult with the lead curator about their addition.

I will keep you updated on this issue if anything arises.

Thank you.

**Comment by ctSkennerton** [comment]
@huynhw1 what was the final decision regarding Tetracenomycin?

**Comment by huynhw1** [comment]
Hello @ctSkennerton ,

The papers supporting the antimicrobial properties of Tetracenomycin C are very limited.
The majority of papers describe it as an tumour antibiotic but not as an antimicrobial antibiotic, which we find to be an important distinction.

As such we have decided to not include Tetracenomycin C in CARD.

Thank you for your patience.
