### ISSUE TITLE
about pass-bitscore confused

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#56]
hi sir:
@arpcard
@apetkau
     a contig was annotated as "tet(W/N/W)" by rgi; but it hit to tetM with  Highest bit-score；
     i found that:
              the pass-bit-score of  tetM  is 1200 ，the contig got bit-score(907) with identity(99%);
              the pass-bit-score of  tet(W/N/W) is 500, the contig got  bit-score(575.9) with identity(67%);
   From the perspective of bit-score and identity，t think this ORF shoud be tetM，not tet(W/N/W) ；
   so How is this pass-bit-score value calculated ？ 

ORF sequence：
`ATGAAAATTATTAATATTGGAGTTTTAGCTCATGTTGATGCAGGAAAAACTACCTTAACAGAAAGCTTATTATATAACAGTGGAGCGATTACAGAATTAGGAAGCGTGGACAAAGGTACAACGAGGACGGATAATACGCTTTTAGAACGTCAGAGAGGAATTACAATTCAGACAGGAATAACCTCTTTTCAGTGGGAAAATACGAAGGTGAACATCATAGACACGCCAGGACATATGGATTTCTTAGCAGAAGTATATCGTTCATTATCAGTATTAGATGGGGCAATTCTACTGATTTCTGCAAAAGATGGCGTACAAGCACAAACTCGTATATTATTTCATGCACTTAGGAAAATGGGGATTCCCACAATCTTTTTTATCAATAAGATTGACCAAAATGGAATTGATTTATCAACGGTTTATCAGGATATTAAAGAGAAACTTTCTGCCGAAATTGTAATCAAACAGAAGGTAGAACTGCATCCTAATATGCGTGTAATGAACTTTACCGAATCTGAACAATGGGATACGGTAATAGAGGGAAACGATTACCTTTTAGAGAAATATATGTCCGGTAAATCATTAGAAGCATTGGAACTCGAACAAGAGGAAAGCATAAGATTTCAGAATTGTTCTCTGTTCCCTCTTTATCATGGAAGTGCAAAAAGTAATATAGGGATTGATAACCTTATAGAAGTTATTACTAATAAATTTTATTCATCAACACATCGAGGTCCGTCTGAACTTTGCGGAAATGTTTTCAAAATTGAATATACAAAAAAAAGACAACGTCTTGCATATATACGCCTTTATAGTGGAGTACTACATTTACGAGATTCGGTTAGAGTATCAGAAAAAGAAAAAATAAAAGTTACAGAAATGTATACTTCAATAAATGGTGAATTATGTAAGATTGATAGAGCTTATTCTGGAGAAATTGTTATTTTGCAAAATGAGTTTTTGAAGTTAAATAGTGTTCTTGGAGATACAAAACTATTGCCACAGAGAAAAAAGATTGAAAATCCGCACCCTCTACTACAAACAACTGTTGAACCGAGTAAACCTGAACAGAGAGAAATGTTGCTTGATGCCCTTTTGGAAATCTCAGATAGTGATCCGCTTCTACGATATTACGTGGATTCTACGACACATGAAATTATACTTTCTTTCTTAGGGAAAGTACAAATGGAAGTGATTAGTGCACTGTTGCAAGAAAAATATCATGTGGAGATAGAACTAAAAGAGCCTACAGTCATTTATATGGAGAGACCGTTAAAAAATGCAGAATATACCATTCACATCGAAGTGCCGCCAAATCCTTTCTGGGCTTCCATTGGTTTA`

**Comment by feihongloveworld** [comment]
@arpcard 
@apetkau

**Comment by huynhw1** [comment]
Hello @feihongloveworld ,

We compare our Tet genes with curated NCBI accessions. So in this case despite the similarities, we cannot call Tet(W/N/W) a TetM because they are different genes.

Tet genes are often similar but they confer resistance differently resulting in a different name.
Bit-scores are calculated manually by a self-blast against our own database.

Thank you.

**Comment by feihongloveworld** [comment]
> Hello @feihongloveworld ,
> 
> We compare our Tet genes with curated NCBI accessions. So in this case despite the similarities, we cannot call Tet(W/N/W) a TetM because they are different genes.
> 
> Tet genes are often similar but they confer resistance differently resulting in a different name.
> Bit-scores are calculated manually by a self-blast against our own database.
> 
> Thank you.



> Hello @feihongloveworld ,
> 
> We compare our Tet genes with curated NCBI accessions. So in this case despite the similarities, we cannot call Tet(W/N/W) a TetM because they are different genes.
> 
> Tet genes are often similar but they confer resistance differently resulting in a different name.
> Bit-scores are calculated manually by a self-blast against our own database.
> 
> Thank you.

夫人烦烦烦

**Comment by feihongloveworld** [comment]
> Hello @feihongloveworld ,
> 
> We compare our Tet genes with curated NCBI accessions. So in this case despite the similarities, we cannot call Tet(W/N/W) a TetM because they are different genes.
> 
> Tet genes are often similar but they confer resistance differently resulting in a different name.
> Bit-scores are calculated manually by a self-blast against our own database.
> 
> Thank you.

hi sir：
    the ORF (orf is not complete, is not end of  stop code) is from my samples，and i blast it to nt database，the best hit is tetM .
   so  the  bit-score of tet(W/N/W)  may not Precise，or it not good work  for partial gene ？ 
  thanks
