### ISSUE TITLE
Requesting community input on renaming dfrA3b to dfrA11 (or dfrA40)

### ISSUE THREAD

**Issue by danielhhaft** [arpcard/amr_curation#57]
Background.

AAN85115.1 currently carries the designation dfrA3b
which suggests a close relationship to  dfrA3.  It's actually quite different, and NCBI has been
asked to change the name of dfrA3b in our antimicrobial resistance database to dfrA40.

dfrA37 = QBL10748.1
dfrA38 = AEH59663.1
dfrA39 = QIM14580.1

dfrA40 is unused, as is dfrA11.

PMID:30989199 (2019) presents a tree of dfrA proteins, and in the legend says  
"DfrA3b (AY162283)  [protein AAN85115.1], which is no longer available in ResFinder, is renamed DfrA11."

 The name "DfrA3b" is central to 3 papers or so, dating from 1990.  The "DfrA3b" is mentioned in maybe 8 publications total, often to provide context.  DfrA3b itself has been sequence  ~8 times, and a contributor to one of those sequencing efforts is requesting the renaming.  

Asking CARD curators and the AMR community - does it seem useful to convert the name DfrA3b to DfrA11 (which somewhat preserves the information that the sequence was first found a fairly long time ago), and list DfrA3b as a synonym,  or rename it to DfrA40, or make no change?  

Personally, I (Daniel Haft) favor keeping the name DfrA3b as it is, since positioning in tree, and the numbering of DfrA families in the order of discovery, are not similar in any way, and all users of the tree will need to suspend belief in the importance of the typographical name, and simply treat it as an arbitrary identifier.

Comments?

**Comment by danielhhaft** [comment]
After some discussion from submitter of one of the multiple dfrA3b sequences, response was 

"Anyway, as you say, dfrA3b is in the literature, and there is no way to eradicate it and no need for a second name."

Also, it was pointed out to me that the name DfrA11 has been used in other ways, albeit incorrectly, it seems.

Unless strong objections pour in during the next few days, I'm inclined to close the case.

**Comment by huynhw1** [comment]
Thank you Daniel!

Keep us updated! I will change it if need be as soon as I am informed.

**Comment by danielhhaft** [comment]
AEH59663.1 is no longer dfrA38. Sequence owner was prevailed upon to change to dfrA43. GenBank was already revised.

This makes room for the dfrA38 described in PMID: 32929451
"A novel trimethoprim resistance gene, dfrA38, found in a sporadic Acinetobacter baumannii isolate"
describing   QNL15203.1

NCBI will add QNL15203.1 as the new and permanent dfrA38.

**Comment by danielhhaft** [comment]
As of November 5 2022, in NCBI's resistance gene catalog,
AAN85115.1  remains dfrA3b   and I reported agreement in a discussion I had, "Anyway, as you say, dfrA3b is in the literature, and there is no way to eradicate it and no need for a second name."
Several months after this ticket was opened, Ambrose and Hall came out, PMID: 34180526, claiming dfrA3b became dfrA11


QBL10748  is now dfrA37 and PMID: 34180526 agrees.

AEH59663 is now dfrA43 and PMID: 34180526 agrees.

QIM14580 is now dfrA39 and PMID: 34180526 agrees.

QNL15203 is now dfrA38 and PMID: 34180526 agrees.

dfrA40 currently unused at NCBI (Ambrose/Hall have EXA67873)
dfrA11  currently unused at NCBI (Ambrose/Hall have the protein from dfrA3b )

Does PMID: 34180526  JAC October 2021 saying dfrA3b has become dfrA11 change anyone's opinion?

**Comment by bpalcock** [comment]
Closing for being outdated. If dfr-related issues are noticed in CARD please open a new issue.
