### ISSUE TITLE
adeF and adeG sequences are reversed

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#58]
hi sir：
       adeF and adeG sequences are reversed
thanks

**Comment by huynhw1** [comment]
Hello @feihongloveworld ,

Thank you for letting us know. We will switch it back around as soon as possible. Expect it to be fixed by next CARD release.

**Comment by huynhw1** [comment]
The issue has been fixed. This will be reflected in the next CARD release.
