### ISSUE TITLE
OXA-427 is Carbapenemase

### ISSUE THREAD

**Issue by hvdheide** [arpcard/amr_curation#59]
A user of our NGS typing service noticed that we missed a Carbapenemase allocation on a found OXA-427 gene. We checked your database, and is it’s not marked yet as a Carbapenemase. 

She supplied the following references:
(1) Bogaerts P, et al. OXA-427, a new plasmid-borne carbapenem-hydrolysing class D ß-lactamase in Enterobacteriaceae. J Antimicrob Chemother 2017;72:2469-77.
(2) Frère J-M et al. Interactions between avibactam and ceftazidime-hydrolyzing class D ß-lactamases. Biomolecules 2020;10:483.

I notified BLDB.eu, and they informed me that the error comes from the NCBI's assignment: for carbapenemases. They use the term "carbapenem-hydrolyzing" (see e.g. OXA-48, 
https://www.ncbi.nlm.nih.gov/protein/WP_015059991.1), whereas for OXA-427 they use only "class D beta-lactamase OXA-427" (https://www.ncbi.nlm.nih.gov/protein/WP_096807440.1).

**Comment by huynhw1** [comment]
Thank you.

Added to OXA-427.
