### ISSUE TITLE
Possibly wrong sequence for pgsA gene Bacillus

### ISSUE THREAD

**Issue by msegurawang** [arpcard/amr_curation#63]
Hi,
If you look at the sequence of the protein described for ARO:3003788 "Bacillus subtilis pgsA with mutation conferring resistance to daptomycin" ([https://card.mcmaster.ca/ontology/40473](https://card.mcmaster.ca/ontology/40473)) it corresponds to a "capsular polyglutamate synthetase" present in several species, including Bacillus (for example: [https://www.ncbi.nlm.nih.gov/protein/NP_391469.1](https://www.ncbi.nlm.nih.gov/protein/NP_391469.1)). All published Bacillus subtilis genomes carry the valine aminoacid in position 64 (which is given in the database as the 'mutation' A64V conferring resistance). If all Bacillus genomes published carry this variant, it is unlikely that this is the real protein described in the reference paper described in the CARD database (Hachmann AB, et al. 2011. [https://aac.asm.org/content/55/9/4326.long](https://aac.asm.org/content/55/9/4326.long).)

On the other hand, there is another gene/protein in Bacillus "CDP-diacylglycerol-glycerol-3-phosphate 3-phosphatidyltransferase" (see for example: [https://www.ncbi.nlm.nih.gov/protein/NP_389574.2](https://www.ncbi.nlm.nih.gov/protein/NP_389574.2) for the B. subtilis 168 WT strain described in the reference paper) which also has the abbreviation pgsA, and which correctly has alanine at position 64 as expected in the wild type strain and other B. subtilis genomes. 
Hachmann et al. refer to the pgsA as being a phosphatidylglycerol synthase, which would fit better to this sequence than to the one present at the moment in the CARD database.

The confusion with the protein sequence might derive from the fact that both proteins have the abbreviation pgsA, although the first protein is also sometimes referred to as capA. 

It would help to clarify which protein sequence is correct to avoid having the impression that all Bacillus have a mutation that confers resistance to daptomycin.

Thanks!

**Comment by huynhw1** [comment]
@msegurawang 

Thanks for pointing this out.
I doubled checked with our other resources and you are indeed correct. I have made the change, but used a different accession because we prefer not using "NP_" accessions. Additionally, the accession we chose has been previously curated by NCBI and by using that one would ensure continuity between databases.

You will see this change reflected in the next CARD update.
