### ISSUE TITLE
VMB-2 class B1 beta-lactamase should be renamed VAM-1 ?

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#66]
This issue was prompted by the recent publication [Identification of a novel plasmid-mediated carbapenemase-encoding gene blaVMB-2 in _Vibrio diabolicus_, Antimicrob Agents Chemother. 2021](https://doi.org/10.1128/aac.00206-21), which reports a new beta-lactamase named VMB-2, although it has only 70 % sequence identity with VMB-1 (as a general rule, which has a few exceptions, the members of existing beta-lactamase families share at least 80 % sequence identity).

In the alignment below, QGQ32905 corresponds to VMB-1 and WP_181726415 to the newly reported sequence :

```
QGQ32905.1          ----MKYIILFLLLIPSIVFANNEGTKELKLKKLSDNVYQHISYKRVEPWGLIGASGLVV	56
WP_181726415.1      MNFLIKNILLITLFVPFVTAANNTDTKTLEVKQLTDNIYQHISYKHVEPWGFIGASGLIV	60
                        :* *:*: *::* :. *** .** *::*:*:**:*******:*****:******:*

QGQ32905.1          INGTEAHMIDTPWTTQGTKQLIEWIEAKGLTIKSAVVTHFHEDASGDIPLLNDLKIKTYA	116
WP_181726415.1      VDGDAAYLIDTPWTTKATNQLIEWIEDRGLVLKSAIVTHFHEDASGDLPLLNDLKVNTYA	120
                    ::*  *::*******:.*:******* :**.:***:***********:*******::***

QGQ32905.1          TSLTNKLLKLNQKEVSSDEISSNTFEFIDGVASVFYPGAGHTEDNIVVWLPNEKILFGGC	176
WP_181726415.1      TSLTNQLLKLNNKEISNTEISSNELKIFNGIATVYYPGPGHTEDNIVVWLPNEKLLFGGC	180
                    *****:*****:**:*. ***** :::::*:*:*:*** ***************:*****

QGQ32905.1          FVKSLKNKNLGYTGDANISEWPNSMQKVINRYPDAKLVVPGHGEVGDVSLLKHTQALALS	236
WP_181726415.1      FVKSLRNKSLGYTGDANIGEWSNSIQRVLQRYPDIVTVVPGHGQVGDVSLLLHTQKLASS	240
                    *****:**.*********.** **:*:*::****   ******:******* *** ** *

QGQ32905.1          AAASNKKINKD	247
WP_181726415.1      DKTSDK-----	246
                      :*:*     
```

The sequence reported in the paper was deposited at the [NCBI](https://www.ncbi.nlm.nih.gov/ipg/WP_181726415.1) by two groups, with the following accession numbers:
- [QJR97743](https://www.ncbi.nlm.nih.gov/protein/QJR97743.1), [QJR97749](https://www.ncbi.nlm.nih.gov/protein/QJR97749.1), [QJR97755](https://www.ncbi.nlm.nih.gov/protein/QJR97755.1) and [QJR97761](https://www.ncbi.nlm.nih.gov/protein/QJR97761.1) from _Vibrio alginolyticus_ strain C1579, submitted on 22-DEC-2019 by Zheng,Z., Ye,L. and Chen,S. (City University of Hong Kong, China) with the name VMB-2
- [QRG84365](https://www.ncbi.nlm.nih.gov/protein/QRG84365.1) from _Vibrio diabolicus_ strain SLV18, submitted on 29-JAN-2021 by Liu,M. (Yangzhou University, China) with the name VMB-2
- [QTJ60982](https://www.ncbi.nlm.nih.gov/protein/QTJ60982.1) from _Vibrio alginolyticus_ strain Vb1579, submitted on 27-MAR-2021 by Zheng,Z. and Ye,L. (City University of Hong Kong, China) with the name VAM-1

The group from City University of Hong Kong, China submitted it first, in Dec 2019, with the name VMB-2, and then again in Mar 2021, this time with the name VAM-1. The group from Yangzhou University, China (which wrote the paper) submitted the sequence in Jan 2021 with the name VMB-2.

Considering all these facts, and especially the low sequence identity between VMB-1 and the newly reported beta-lactamase, I would suggest to use from now on the name VAM-1 for this sequence (name chosen by the group from City University of Hong Kong, China, which first reported this sequence) and to include it in our databases with this name.

Any thoughts about this issue are welcome. Thank you in advance.

**Comment by feldgard** [comment]
Iorga,

The VAM-1 submitter contacted us at NCBI, and we recommended the name change for the same reasons you did, so we endorse your suggested change.

Mike Feldgarden
NCBI/NLM/NIH

**Comment by iorga** [comment]
Thank you, @feldgard . I'm glad that we are on the same page on this issue.

How do you think that we should inform the community about this change? I propose to:
1. Write to the authors of the paper, asking them to publish an "Author Correction" in AAC with the new name of the beta-lactamase.
... and, if not successful ...
2. Write a "Comment Letter" to the Editor of AAC, if possible together with the group from the City University of Hong Kong that submitted VAM-1 first.

Bogdan Iorga
BLDB, CNRS-ICSN, France

**Comment by iorga** [comment]
The group from Hong Kong has just published a paper in AAC reporting VAM-1 (https://doi.org/10.1128/aac.01129-21), so I consider that the issue is closed now.
