### ISSUE TITLE
ARG to antibiotic class

### ISSUE THREAD

**Issue by pdhrati02** [arpcard/amr_curation#70]
Hi,
Thank you for the CARD database, it is very helpful.
I have one question: I am using the software version and the output we get is xyz ARF present in each sample/MAG. Is there a phenotype file for CARD database which can be used to give broader classification to these ARGs? Thus grouping them further? 

Thank you in advance
DP

**Comment by bpalcock** [comment]
Closed for being outdated. Please reopen if help is still needed.
