### ISSUE TITLE
synchronize swap of ROB alleles, old ROB-2 to ROB-13, old ROB-9 to ROB-2, across multiple databases.

### ISSUE THREAD

**Issue by danielhhaft** [arpcard/amr_curation#73]
NCBI began coverage of the blaROB family in 2018.

A work in progress in 2018, published in 2019 (Kadlec, et al., PMID:30561662), gave characterized
protein AWU47610.1 the tentative allele name blaROB-2.  Upon review of the family, we found our
assignments differ.  AWU47610.1 was called blaROB-9 at NCBI, and AGH37381.1 was called  blaROB-2.

NCBI has decided to change allele assignments to match the usage of Kadlec, et al.
AWU47610.1 previously called blaROB-9, will now be called blaROB-2.
AGH37381.1, previously called blaROB-2, now will be called ROB-13.
The allele designation blaROB-9 will declared a dead allele, and have no protein assigned to it.

Note that the new ROB-2 is an extended-spectrum beta-lactamase (ESBL), and is the currently the only one 

Users of NCBI's Pathogen Detection system and AMR database should expect to see the corrected  assignments
publicly by mid-June.

**Comment by smithk63** [comment]
Hi Dr. Haft,

Thank you for letting us know. These upcoming changes to allele assignments will be reflected in our next CARD release.

Thank you,

Keaton Smith
Developer Assistant Co-op Student
CARD Junior Curator & Help Desk

**Comment by arpcard** [comment]
CARD has been updated with these corrections: https://card.mcmaster.ca/ontology/39428
