### ISSUE TITLE
lnuB and lsaE are identical

### ISSUE THREAD

**Issue by MBiggel** [arpcard/amr_curation#78]
Hi,

the sequences of lnuB and lsaE are identical.
Should these be merged?

Thanks,
Michael

**Comment by MBiggel** [comment]
Actually the lsaE sequence listed in the Resfinder database is missing in CARD?

**Comment by smithk63** [comment]
Hi Michael,

This looks like a curation error where the lsaE sequence added was nearly identical to lnuB, so we appreciate you spotting this for us. The sequence for lsaE has been updated and should be visible in the next public release.

Thanks,

Keaton Smith
Developer Assistant Co-op Student
CARD Junior Curator & Help Desk
