### ISSUE TITLE
Question on sequence update of mecC-type BlaZ gene in CARD v 3.1 to 3.2

### ISSUE THREAD

**Issue by katrinakalantar** [arpcard/amr_curation#79]
Hello! I have a question about a sequence update (details below) and was curious to learn more about how the decision was made to update this sequence / the evidence for or against the initial sequence. We were seeing some interesting hits to the old sequence, but it seems to no longer be in the databases. Any additional information would be much appreciated.

The changelog from CARD DB  `v3.1.4` to `v3.2.0` indicates that the sequence of mecC-type BlaZ was updated from `FR823292` to `FR823292.1`, which has an entirely different (apparently non-overlapping) sequence.

> 3829	UPDATE	mecC-type BlaZ	 penam;  antibiotic inactivation;  BlaZ beta-lactamase;  penicillin; 	ARO_description; model_sequences; ARO_category	"UPDATED ARO_description with A blaZ-like beta-lactamase found in S. Aureus.
> UPDATED partial with 0
> UPDATED sequence with TTGAAAAAATTAATAATTTTAGTCGTGTTAGCGTTGATATTAAGTGCTTGTAATAGTAAGAATTCAACTAATAACGACATTGAAAAGATCGAAAAAAAATATGGTGCTAACGTAGGTATGTATGCTCTTAATACTCAAAATGGTAAAGAATTATCATTTAATGAAAATAAGCGTTTTGCATATGCTTCCACATTAAAAACTATAAGTAGCGCAATGCTGCTTGAACAAACACCTTACAACAAATTAGATAAAAAAATTCACATTAATAAAGATGATATTGTTCCATATTCACCAGTGTTAGAAAAATATATTGGCAAAGAGATAACTTTAAAAAAGCTTATAGAAGCTACCATGTTATTTAGCGATAACACGGCTAATAATAAAATTATCGATGAATTGGGAGGATATGGGCAAGTAAAAACGAAACTGATAGATTTAGGCGATACAACGACACATCCATCTAGAAAAGAACCAGACTTAAATTTTTATTCACCAAAGGATAAACGAGATACAAGTACTCCATTAGCCTATGGTAAAACTTTAAAGAAACTTATAGCTGATGGAGATCTTAGCAAAGCAAACAAAGATTTCTTACTTAATCTAATGTTCAAAAATAAAAGTGGCGATACATTAATTAAGGATGGTGCACCTTCAAACTTTAAAGTTATGGATAAGAGCGGTCAAGCACTAACATACGGTTCAAGAAACGATGTTGCGTTTGTTTATCCAGATGGACAAGATAAACCTATAATTCTGGTGATATTTACAAATAAAGATAGAAAAGATGGTAAACCTAATGACAAAATAGTAAGTGAGGTTGCTGAAATTGTACTAAAAAATATTAATGAGTAA
> UPDATED fmax with 1647
> UPDATED accession with FR823292.1

[for reference, the sequence was in CARD DB v. `3.1.4`]

> gb|FR823292|+|0-480|ARO:3005097|mecC-type BlaZ [Staphylococcus aureus] Partial
> ATGAAAATCACCATTTTAGCTGTAGGGAAACTAAAAGAGAAATATTGGAAGCAAGCCATAGCAGAATATGAAAAACGTTTAGGCCCATACACCAAGATAGACATCATAGAAGTTCCAGACGAAAAAGCACCAGAAAATATGAGCGACAAAGAAATCGAGCAAGTAAAAGAAAAAGAAGGGCAACGAATACTAGCCAAAATCAAACCACAATCAACAGTCATTACATTAGAAATACAAGGAAAGATGCTATCTTCCGAAGGATTGGCCCAAGAATTGAACCAACGCATGACCCAAGGGCAAAGCGACTTTGTATTCGTCATTGGCGGATCAAATGGCCTGCACAAGGACGTCTTACAACGCAGTAACTACGCACTATCATTCAGCAAAATGACATTTCCACATCAAATGATGCGGGTTGTGTTAATTGAGCAAGTGTATAGAGCGTTTAAGATTATGCGCGGAGAAGCGTATCACAAATGA

**Comment by danielhhaft** [comment]
(NCBI member Daniel Haft here, taking a quick look)
The old sequence translates to WP_000704775.1, 23S rRNA (pseudouridine(1915)-N(3))-methyltransferase RlmH.
That should be just a housekeeping gene, not an antimicrobial resistance gene, so it looks like CARD had that particular sequence by mistake.

The new sequence translates to CBZ41939.1, protein product of the blaZ gene of the mecZ  locus.
CBZ41939.1 is the correct protein.

Since CARD's change appears to have been simply a case of replacing the wrong sequence with the right one, I imagine this ticket could be resolved now.

**Comment by bpalcock** [comment]
Very delayed response but Dan is correct - this does happen occasionally when an incorrect sequence is grabbed by mistake
