### ISSUE TITLE
class A CAE-1 beta-lactamase

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#83]
Hello,

A new class A beta-lactamase, named CAE-1, was described and characterized in a recent paper (https://doi.org/10.1038/s41598-023-28312-w). However, only the complete sequence of the plasmid containing this beta-lactamase was deposited at the NCBI (https://www.ncbi.nlm.nih.gov/nuccore/CP104280) and currently no individual entry is available in GenBank or RefSeq for CAE-1.

@danielhhaft Would it be possible to create a RefSeq entry for this beta-lactamase starting from the deposited plasmid, or it is mandatory that the authors submit the individual sequence to GenBank ?

Thanks,
Bogdan

**Comment by danielhhaft** [comment]
Hi Bogdan,

Thank you for creating this ticket.  In response, NCBI has now created a new HMM (NF041590) that will name full-length members of the broader family "CAE family broad-spectrum class A beta-lactamase".  

Plasmid CP104280 currently does not have annotated features, but a reannotation of the plasmid by NCBI is available as NZ_CP104280, and CAE-1 shows up as WP_158386862.1.

Submitting sequences nucleotide records encoding individual antimicrobial resistant proteins (beta-lactamases, MCR proteins (colistin resistance), and Qnr proteins (quinolone resistance) to NCBI for inclusion in GenBank, with a request for allele assignment, remains the only to reserve an allele assignment and avoid risks of nomenclature collisions if your own or someone else's sequence is not yet publicly released.  We therefore encourage advance consultation. When we process sequences for which alleles are requested in advance, the allele assignment becomes part of GenBank's archive of annotated sequence submissions. 

However, we are also capable of responding to allele requests for sequences already publicly released. In these cases, a RefSeq protein, with an accession number beginning "WP_", will appear, at our next release, with correct annotation, but there should be no expectation that sequences previously available from GenBank/EBI/DDBJ records will be reannotated.

NCBI would like to initiate coverage of the CAE family for future allele assignments, given that CAE-1 is plasmid-borne, demonstrated to occur in hospital wastewater, and seen already in multiple species including the important pathogen Pseudomonas aeruginosa.

CAE-1 will be found in our next release.

Daniel Haft
NCBI

**Comment by iorga** [comment]
Many thanks Dan for the fast reply and for identifying the NCBI entry corresponding to CAE-1. The issue is now solved.
