### ISSUE TITLE
beta-lactamase families RSA1 and RSA2

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#84]
Hello,

In CARD there are two entries, one for the RSA-1 beta-lactamase (https://card.mcmaster.ca/ontology/41637) and one for RSA2-1 (https://card.mcmaster.ca/ontology/45443). Both were described in the paper [Marathe et al 2018](https://doi.org/10.1016/j.envint.2017.12.036).
1. RSA-1 should be renamed RSA1-1 in CARD, for compatibility with [NCBI](https://www.ncbi.nlm.nih.gov/ipg?term=WP_223292485) and [BLDB](http://bldb.eu/BLDB.php?prot=A#RSA1). @agmcarthur
2. The same reference [Marathe et al 2018](https://doi.org/10.1016/j.envint.2017.12.036) should be added to RSA2-1 in CARD. @agmcarthur
3. I am in contact with Dr Fang, author of the paper "Genomic analysis of chromosomal cointegrated blaNDM-1-carrying ICE and blaRSA-1-carrying IME from clinical multidrug resistant Aeromonas caviae" (https://doi.org/10.3389/fcimb.2023.1131059). The beta-lactamase that they have identified (referred to incorrectly as blaRSA-1) is in fact [WP_216944871](https://www.ncbi.nlm.nih.gov/ipg/?term=WP_216944871) and dosn't have an allele number assigned. @danielhhaft , can you please assign an allele number (e.g. RSA1-2) for it in NCBI ?

Thanks,
Bogdan

**Comment by arpcard** [comment]
Updated names in CARD
