### ISSUE TITLE
Addition of Bedaquiline sequences

### ISSUE THREAD

**Issue by pratibha-kadam** [arpcard/amr_curation#87]
Hello there,

I am working with AMR data and I am finding CARD very useful.

Just need to add AMR genes regarding Bedaquiline.
As Bedaquiline is a drug for MDR TB. It makes it important to check the surveillance of the BDQ genes.

Please add BDQ resistance genes in CARD DB.

**Comment by bpalcock** [comment]
Hi Pratibha, CARD does contain a few genes linked to bedaquiline resistance in TB, see: https://card.mcmaster.ca/ontology/41933

If there are others you are aware of not listed here could you please send a link or list of accessions and/or pubs? I can then have a curator review them
