### ISSUE TITLE
EstT Drug Class Misslabelled

### ISSUE THREAD

**Issue by DanCWB** [arpcard/amr_curation#88]
Hello,

_estT_ has as drug classes: tetracycline antibiotic, glycylcycline, macrolide antibiotic, listed.
However the attached publication to the entry only shows activity to macrolides.
Unless there is some publication on _estT_ that I'm unaware of that shows it confers resistance to tigecycline, could you remove these tags?

https://card.mcmaster.ca/ontology/46222

A further, smaller issue is that the first letter of the gene _estT_ is capitalized when it shouldn't be.

Thanks,
Daniel

**Comment by springwang24** [comment]
Hello Daniel,

Thank you for bringing this to our attention. You are correct that the attached publication does not explicitly show _estT_ confers resistance to tigecycline. "Incredibly, estT has been overlooked despite preeminent reports of it within emerging tigecycline resistance loci " is the only mention of tigecycline resistance although the two publications linked with this claim also do not explicitly show _estT_ and tigecycline resistance. We have removed these tags as we are unable to find other research with this relationship. This change will be reflected in the next CARD release.

The capitalization of _estT_ in CARD is more of a continuity choice as most of our gene names are capitalized but we can discuss the possibility of changing them. 

Thanks,
Spring
