### ISSUE TITLE
MdfA resistant to multidrug?

### ISSUE THREAD

**Issue by danrlu** [arpcard/amr_curation#91]
Currently E coli MdfA is listed as resistant to tetracycline antibiotics: https://card.mcmaster.ca/ontology/37727
This paper was showing its ability to resist to multiple drug classes (is that right?)
https://www.pnas.org/doi/10.1073/pnas.0435544100

A physician collaborator pointed this out and I wanted to relay the msg.

**Comment by springwang24** [comment]
Hi Dan,

Thanks for informing us. After reading the paper you attached, we agree _confers_resistance_to_antibiotic_ relationships should be added to MdfA to chloramphenicol and thiamphenicol. We have added these relationships to the term in CARD and this change will be made public on our next release. Thanks for the insight!

Spring
