### ISSUE TITLE
Complete sequence for OXA-410 beta-lactamase

### ISSUE THREAD

**Issue by iorga** [arpcard/amr_curation#92]
In the Lahey repository, the allele number was assigned to a partial sequence for [OXA-410](https://www.ncbi.nlm.nih.gov/protein/AJD77428) (last residue missing). Now a [complete sequence](https://www.ncbi.nlm.nih.gov/protein/HCT5551642.1) is available, which should replace the old one.

**Comment by bpalcock** [comment]
this is now updated in CARD! will be pushed in the next release
