### ISSUE TITLE
blaGES genes discrepancies

### ISSUE THREAD

**Issue by TomJove** [arpcard/amr_curation#93]
Dear ARPCARD amr_curation team,

I went through the diversity of blaGES genes and corresponding b-lactamases GES proteins and noticed some discrepancies I'd like to point out:
- The ARPCARD reference blaGES-7 gene does not encode the same protein as the NCBI NDARO blaGES-7 gene. BLDB uses the same blaGES-7 as ARPCARD.
- blaGES-47 to blaGES-59 genes (listed in NDARO) are absent in ARPCARD
- Found three more blaGES not numbered yet alleles.

==> My blaGES alleles description, sequences and more information about these discrepancies are freely available for download here:  https://tinyurl.com/blaGES-4032024

I am currently going on with more genes and progress are available here: 
https://sites.google.com/view/thomasjove/analysis

Best,
Thomas

**Comment by bpalcock** [comment]
Hi Thomas, the peptide accession for GES07 in CARD ([AAP22974.1](https://www.ncbi.nlm.nih.gov/protein/AAP22974.1)) is listed as an identical protein for the NDARO GES-7 accession ([AAF28763.2](https://www.ncbi.nlm.nih.gov/protein/AAF28763.2)), as is the BLDB accession ([ADU79013](http://www.ncbi.nlm.nih.gov/protein/ADU79013)).

For alleles GES-47 to GES-59, we tend to update beta-lactamases periodically in bulk so I will add these in for the next such update.

Thanks,
Brian

**Comment by TomJove** [comment]
Thank you for replying! My apologies for GES-7, seems I have been confused but indeed both sequences are the same.

**Comment by bpalcock** [comment]
Hi Tom, just letting you know these missing sequences were added in the most recent CARD release.
