### ISSUE TITLE
blaVIM genes update

### ISSUE THREAD

**Issue by TomJove** [arpcard/amr_curation#94]
Dear ARPCARD amr_curation team,

I went through the diversity of blaVIM genes and corresponding b-lactamases VIM proteins and noticed some recently reported blaVIM alleles were absent, namely blaVIM-74 to blaVIM-86.
My current progress on these genes is available here:
https://sites.google.com/view/thomasjove/analysis
and for direct download here: https://tinyurl.com/blaVIM-6032024

What is your (and NDARO's) policy for the blaVIM-21 and blaVIM-22 sequences from Lahey's list the sequence of which has not been shared ? To let them absent until their sequence eventually become public or to assign these numbers novel sequences ? 
Thank you

Best,
Thomas

**Comment by bpalcock** [comment]
Hi Tom, I completed an update for the missing VIM beta-lactamases and these should be included in the current release.

As for your question about VIM-21/22 - we defer to NCBI for decisions about how these numbers get reused, though I believe the current policy is to keep these numbers reserved/retired and not assign these numbers novel sequences.
