### ISSUE TITLE
Alignment result not shown when Blasting

### ISSUE THREAD

**Issue by yondchang** [arpcard/amr_curation#95]
I was using CARD blast to search AMR genes, when I click the View link on the Alignment column, it just shows a blank page.

![screenshot](https://github.com/arpcard/amr_curation/assets/8464964/3c0179b8-e992-4c2f-b90e-3e3fe590439f)

**Comment by TomJove** [comment]
Hi,
Have the same issues. I overcome this by downloading the ARG list and running blastP on the online NCBI server.
Hope it helps
Thomas
