### ISSUE TITLE
 Novel tetracycline resistance gene tet(65) 

### ISSUE THREAD

**Issue by TomJove** [arpcard/amr_curation#96]
Dear ARPCARD curator team,

This novel gene is absent from ARPCARD (from NDARO as well):

Protein RefSeq:WP_010154754.1
Nucleotide entry: CP123906
Now published as PMID38497972

Good luck,
Thomas

**Comment by bpalcock** [comment]
Hi Thomas, this has been added to CARD and will be present in the next release, scheduled for early August. 
Thanks,
Brian
