### ISSUE TITLE
Ciprofloxacin Tolerance Gene in Acinetobacter baumannii

### ISSUE THREAD

**Issue by AndreaAuchincloss** [arpcard/amr_curation#98]
Hi, I'm an annotator at UniProtKB/Swiss-Prot. I saw this paper (PMID 33820764) which refers to this protein AKA29893.1 and confers tolerance to ciprofloxacin. I've added it to Swiss-Prot (it won't be public for a few months) and thought you might be interested too. I don't think it is already in CARD, I ran a BLAST and didn't find the protein. Is there a way to search CARD by PMID? I've looked and haven't found one...
Best regards, Andrea Auchincloss

**Comment by agmcarthur** [comment]
This is now implemented in the CARD website search box.
