### ISSUE TITLE
Clinical Relevance

### ISSUE THREAD

**Issue by tibitoy** [arpcard/amr_curation#99]
Hi! I was wondering how CARD determines whether or not an ARG is of clinical relevance? Is there a separate database to be used if one is only interested in clinically relevant ARGs? I was using Nanopore EPI2ME's ARMA, which maps long reads against the CARD database. It also allows you to sort genes by clinical relevance. When I asked Nanopore how they are determining clinical relevance, they said that CARD provided that information but I can't seem to find anything online indicating that.

**Comment by agmcarthur** [comment]
Answered by email as well, but posting answer here for all:

>  CARD does not yet annotate the epidemiology of ARGs (i.e., which are clinical) nor do we have the data underlying EPI2ME. However, we recently released our updated metagenomics bait capture platform and hand-curated a list of clinical ARGs. You can view the pre-print here: https://www.biorxiv.org/content/10.1101/2024.03.27.587061v1. The associated data is available for download at the CARD website.
